insert into curso (id, nome)
values     (default, "Direito"),
        (default, "Arquitetura e Urbanismo"),
        (default, "Biomedicina"),
        (default, "Educação Física"),
        (default, "Enfermagem"),
        (default, "Estética e Cosmética"),
        (default, "Farmácia"),
        (default, "Fisioterapia"),
        (default, "Nutrição"),
        (default, "Serviço Social"),
        (default, "Comunicação Social - Rádio e TV"),
        (default, "Design Gráfico"),
        (default, "Jornalismo"),
        (default, "Publicidade e Propaganda"),
        (default, "Ciência da Computação"),
        (default, "Engenharia Civil"),
        (default, "Engenharia de Produção"),
        (default, "Engenharia Elétrica"),
        (default, "Engenharia Mecânica"),
        (default, "Gestão da Tecnologia da Informação"),
        (default, "Pedagogia"),
        (default, "Administração"),
        (default, "Ciências Contábeis"),
        (default, "Gastronomia"),
        (default, "Gestão Comercial"),
        (default, "Gestão de Recursos Humanos"),
        (default, "Logística"),
        (default, "Marketing");

insert into periodo (id, periodo)
value    (default, "Primeiro"),
        (default, "Segundo"),
        (default, "Terceiro"),
        (default, "Quarto"),
        (default, "Quinto"),
        (default, "Sexto"),
        (default, "Sétimo"),
        (default, "Oitavo"),
        (default, "Nono"),
        (default, "Décimo");
        
